name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/day8/chrome-latest:5.1.0
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: 'npm install'
      - name: run tests
        run: npm run ci